// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Environment is the predicate function for environment builders.
type Environment func(*sql.Selector)

// Network is the predicate function for network builders.
type Network func(*sql.Selector)

// Node is the predicate function for node builders.
type Node func(*sql.Selector)
